server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location /prod-api/ {
        proxy_pass http://zhcp-api:18088/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
        client_max_body_size 80m;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
